name       : python-contourpy
version    : 1.0.6
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/c/contourpy/contourpy-1.0.6.tar.gz : 6e459ebb8bb5ee4c22c19cc000174f8059981971a33ce11e17dddf6aca97a142
homepage   : https://github.com/contourpy/contourpy
license    : BSD-3-Clause
component  : programming.python
summary    : Python library for calculating contours in 2D quadrilateral grids
description: |
    ContourPy is a Python library for calculating contours of 2D quadrilateral grids. It is written in C++11 and wrapped using pybind11.
builddeps  :
    - pkgconfig(python3)
    - pybind11
    - python-build
    - python-installer
rundeps    :
    - numpy
build      : |
    %python3_setup
install    : |
    %python3_install
